### ISSUE TITLE
[Webplugin] "Merged" links causes awkward overflow in Terms & Conditions

### ISSUE THREAD

**Issue by Malvoz** [pollfish/docs#6]
![docs_pollfish](https://user-images.githubusercontent.com/26493779/57735452-f47c1f00-76a4-11e9-86d5-6b5f1c5ec1b9.png)

As a quick fix, setting (e.g.) `html { overflow-wrap: break-word; }` resolves the issue as shown below:

![docs_pollfish_fix](https://user-images.githubusercontent.com/26493779/57735709-d662ee80-76a5-11e9-8002-6f4d1b44a304.png)

**Comment by spideynr** [comment]
Nice catch @Malvoz, thank you for reporting this. I will be fixing this on the next release within the day. 

PS: I am still using the `word-wrap` property, i had no idea `overflow-wrap` existed!
