### ISSUE TITLE
[WebPlugin] "ToU & Privacy Policy" link returns 403 forbidden

### ISSUE THREAD

**Issue by Malvoz** [pollfish/docs#7]
Steps to reproduce:

1. Visit https://www.pollfish.com/webplugin/
2. Click on the Pollfish Indicator > "Start Survey" > the link: "ToU & Privacy Policy"
3. Fetch returns 403, resulting in a blank page.

As an aside, `https://cdn.segment.com/analytics.js/v1/f00bar/analytics.min.js` is also fetched and returns 403 at the same time.

**Comment by spideynr** [comment]
Hi again @Malvoz !

it seems to work on our end and the tests on the CI pass, but i do get error events from that link. So i have pinpointed it and tasked with resolving it tomorrow. Thanks for pointing it out!

**Comment by Malvoz** [comment]
> it seems to work on our end

I'm not using any browser extensions, on Windows 10 with Chrome 74.0.3729.157. I also tried on some very recent versions of Edge and Firefox resulting in the same issue... weird.

**Comment by spideynr** [comment]
Deployed the fix in production today @Malvoz, thanks again for pointing out. It should work as expected.
